Di ← ≡(=°□:) ⊃(+1 ×2 ⇡ -1|□ ⊞+.⇡)

G!! = (
  ⊃((0|+1 ⊢⊚⇌) =1 /+. ^1 ⇌ ⍉
   |(0|+1 ⊢⊚ ) =1 /+. ^1)
  +×100:
)

# Part 1
FindEq ← ⊞≍ . ≡□
Fm ← ≡(≍×,°□:) Di ⊢ △ . □
Gmi ← G!!(Fm FindEq|Fm FindEq)

# Part 2
AlmostEq ← ×<3 .+1 -:⊢ ⊢ . ⊞(/+= °□:°□) . ≡□
Fs ← ≡(×⊃(=1/+=2|¬∊0) -1 ↘÷2⧻. ▽≠0. ♭+×,°□:) Di ⊢ △ . □
Gsi ← G!!(Fs AlmostEq|Fs AlmostEq)

# Input
⊕□⍜▽¯:\+.=, @\n &fras "input"
&p /+ ⊜(Gmi ≡(°□)) ≠, □ "" .
&p /+ ⊜(Gsi ≡(°□)) ≠, □ ""
